Part 2 design using html css
araraltawarah98/assigments pull request #2
Opened 2021-03-21 13:48 UTC by araraltawarah98

2021-03-21 14:39 UTC, abood454 requested changes
The Design is good but I think the spaces between elements and elements sizes can be more accurate.

2021-03-21 14:39 UTC, abood454 commented on task_1/index.html
> +          <div class="coffee-item">
the cards should have border 
and the text should be bigger

2021-03-21 14:39 UTC, abood454 commented on task_1/index.js
> +const onMenuItemClick = (elementId) => {
I think there is a bug in "our lands".
if you turn off our lands button and you try to turn it on again, the button will stop working.

2021-03-21 14:39 UTC, abood454 commented on task_1/style.css
the alphabetical order is missing

2021-03-21 20:47 UTC, ashrafabuodeh requested changes

2021-03-21 20:47 UTC, ashrafabuodeh commented on task_1/index.html
> +        <img src="./assets/images/Double espresso-1.png" alt="">
write alternative for image if the image not visible

2021-03-21 20:47 UTC, ashrafabuodeh commented on task_1/index.js
> +};
add space here

2021-03-21 20:47 UTC, ashrafabuodeh commented on task_1/style.css
remove space

2021-03-21 22:14 UTC, Mohsen-Awad requested changes

2021-03-21 22:14 UTC, Mohsen-Awad commented on task_1/style.css
> +  margin-right: auto;
use shorthand margin

2021-03-22 12:40 UTC, mmasaid commented on task_1/index.js
> +    if (items[i].className.includes(active) === true) {
There is no need to mention === true _here_ 
```suggestion
    if (items[i].className.includes(active)) {
```

2021-03-22 18:31 UTC, laithyounes requested changes

2021-03-22 18:31 UTC, laithyounes commented on task_1/index.html
> +        <img src="./assets/images/MOcha Late 02.png" alt="">
change the image `src` and image name here,
this will freakout on some OS/browsers

2021-03-22 18:31 UTC, laithyounes commented on task_1/index.html
> +        <img src="./assets/images/MOcha Late 02.png" alt="">
and please add `alt`

2021-03-23 07:53 UTC, abood454 approved these changes

2021-03-23 07:54 UTC, ashrafabuodeh approved these changes

2021-03-23 07:57 UTC, Mohsen-Awad approved these changes

2021-03-24 11:55 UTC, mmasaid commented on task_1/index.js
> +  const itemId = document.getElementById(elementId);
```suggestion
  const navItem = document.getElementById(elementId);
```

2021-03-24 11:58 UTC, mmasaid approved these changes
LGTM

2021-03-24 13:19 UTC, merged