Part 3 responsive layout
araraltawarah98/assigments pull request #4
Opened 2021-03-24 13:42 UTC by araraltawarah98

2021-03-28 12:54 UTC, abood454 approved these changes

2021-03-30 06:51 UTC, ashrafabuodeh approved these changes

2021-03-30 06:54 UTC, Mohsen-Awad approved these changes

2021-03-30 10:27 UTC, mmasaid commented on task_1/.vscode/settings.json
> +}
No need for the VS setting
```suggestion
```

2021-03-30 10:28 UTC, mmasaid commented on task_1/index.html
> +        <img src="./assets/images/menu-button-of-three-horizontal-lines.png" alt="menu icon">
```suggestion
        <img src="./assets/images/menu-button-of-three-horizontal-lines.png" alt="Menu Icon">
```

2021-03-30 10:29 UTC, mmasaid commented on task_1/index.js
> +  document.querySelector(".header .menu").classList.toggle('display-toggle');
👍

2021-03-30 10:31 UTC, mmasaid commented on task_1/style.css
> +  min-width: 500px;
```suggestion
   min-width: 500px;
   width: 50%;
```

2021-03-30 10:43 UTC, mmasaid commented on task_1/style.css
> +    display: block;
Use flex direction
```suggestion
....
```

2021-03-30 10:46 UTC, mmasaid commented on task_1/style.css
> +    z-index: 1;
No need for Z-index
```suggestion
```

2021-03-30 10:54 UTC, mmasaid requested changes
CR: address the comments
FR: Need to handle the flex-box

2021-03-30 13:46 UTC, mmasaid approved these changes

2021-03-31 08:06 UTC, merged